name: Build ZMK Sofle (Dongle)
on:
  push:
    paths:
      - "config/eyelash_sofle.keymap"
      - "dongle/**"
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: dongle/config
      build_matrix_path: dongle/build.yaml
      archive_name: firmware-dongle
