name: Build ZMK Sofle (Direct)

on:
  push:
    paths:
      - "config/keys.keymap"
      - "sofle/**"
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-user-config.yml
    with:
      config_path: sofle/config
      build_matrix_path: sofle/build.yaml
      archive_name: firmware-sofle
